apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-v1.yaml
  - deployment-v2.yaml
  - service-v1.yaml
  - service-v2.yaml

    # commonLabels:
    #  author: kustomize-example

patches:
  - path: increase_replicas_v1.yaml
  - path: set_memory_v1.yaml 
